---
title: "PRF_plotting"
output: html_document
---

# Imports


```{r setup}
library(ggplot2)
library(ggforce)
library(mixtools)
library(cowplot)
```

# Read in data

```{r}
myfile=read.csv('/Volumes/BAHAMUT/OUTPUT/prfparams.csv')
head(myfile)
```


```{r}
nROIS=length(unique(myfile$ROI))
facetval=floor(sqrt(nROIS))

recipe=list(scale_fill_manual(values=c("steelblue2","springgreen3")),theme_classic())

```



# Fit a gaussian mixture model (2 gaussians to the distribution of variance explained)
```{r}
library(mixtools)
out<-normalmixEM(myfile$R2[!is.na(myfile$R2)],k=2)
```


Use this to define a threshold, whereby there is a low probability that the voxel belongs to the noise pool

```{r}
thresh=out$mu[1]+(1.96*out$sigma[1])

myfile$noisesep=factor(ifelse(myfile$R2<thresh,0,1),levels=c(0,1),labels=c("noise","signal"))

varex=ggplot(data = myfile,aes(x = R2))+geom_histogram(color="black",aes(fill=noisesep),binwidth=.01, position="identity")+geom_vline(xintercept=thresh)+recipe
varex
```


This would appear to capture the distributions fairly well


```{r}
varexROI=ggplot(data = myfile,aes(x = R2))+geom_histogram(color="black",aes(fill=noisesep),binwidth=.01, position="identity")+geom_vline(xintercept=thresh)+facet_wrap(~ROI,nrow=facetval)+recipe
varexROI
```






```{r}
myfile_denoised=na.omit(myfile[myfile$noisesep=="signal",])
ggplot(myfile_denoised,aes(x = reorder(ROI, R2, FUN = mean),y=R2))+recipe+stat_summary(fun.y = mean, geom = "bar", width = 0.5)+stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.3)

```


```{r}
VFplot=ggplot()+geom_hline(yintercept=0,colour='white')+
theme_classic()+theme(panel.background = element_rect(fill='black'))+geom_vline(xintercept=0,colour='white')+geom_circle(data=myfile_denoised,mapping=aes(x0=X,y0=Y,r=S/2),fill='white',alpha=.1,colour='transparent')+xlim(-10,10)+ylim(-10,10)+coord_fixed()+facet_wrap(~ROI,nrow=facetval)
VFplot
```

```{r}
cart2pol(c(-10,1))
```
```{r}
VFplot=ggplot()+geom_hline(yintercept=0,colour='white')+
theme_classic()+theme(panel.background = element_rect(fill='black'))+geom_vline(xintercept=0,colour='white')+geom_circle(data=myfile_denoised,mapping=aes(x0=X,y0=Y,r=S/2,color=ROI),alpha=.1)+xlim(-10,10)+ylim(-10,10)+coord_fixed()
VFplot
```


```{r}
ggplot(myfile_denoised,aes(x=Y,y=X))+geom_point()+coord_polar()
```

